### ISSUE TITLE
pre-training model

### ISSUE THREAD

**Issue by jingziyou** [AmeryXiong/MixDehazeNet#1]
Hi,
when the pre-training model will be released？

**Comment by AmeryXiong** [comment]
I will upload as soon as possible.

**Comment by DeTeam** [comment]
Would be great to be able to get the weights and play around locally with inference 🙏 🤩

**Comment by AmeryXiong** [comment]
I will update the most version code and weights in today or tomorrow. Sorry. i am little busy.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AmeryXiong** [comment]
I have updated !

**Comment by PINTO0309** [comment]
@AmeryXiong 

Thank you!

It appears that read access rights have not been granted to the Google Drive URL in the pre-trained model.
Can you grant read permission so that everyone can download the file?

**Comment by AmeryXiong** [comment]
hi, I have granted permission to everyone!

**Comment by PINTO0309** [comment]
@AmeryXiong 
Hmmm...I still get a screen saying I don't have permissions when I click on the README link. 

Although the screen is in Japanese, it means `Access rights required` in English.
![image](https://github.com/AmeryXiong/MixDehazeNet/assets/33194443/052583a9-0e06-4183-8022-037f91c3c876)

**Comment by AmeryXiong** [comment]
Maybe it is ok now! You can try again.

**Comment by PINTO0309** [comment]
It worked! Thanks! :+1: 
![image](https://github.com/AmeryXiong/MixDehazeNet/assets/33194443/398c4c29-200e-4b67-b819-59ad78323886)

**Comment by DeTeam** [comment]
Thanks @AmeryXiong! 
Tried model-s + outdoor, looks good! 

For model-s and indoor, however, I get size mismatch for a whole bunch of blocks.
Do you know what might be causing the issue?


Partial log sample:

```
RuntimeError: Error(s) in loading state_dict for MixDehazeNet:
	size mismatch for layer1.blocks.0.mlp.0.weight: copying a param with shape torch.Size([96, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([96, 72, 1, 1]).
	size mismatch for layer1.blocks.0.mlp2.0.weight: copying a param with shape torch.Size([96, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([96, 72, 1, 1]).
	size mismatch for layer1.blocks.1.mlp.0.weight: copying a param with shape torch.Size([96, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([96, 72, 1, 1]).
	size mismatch for layer1.blocks.1.mlp2.0.weight: copying a param with shape torch.Size([96, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([96, 72, 1, 1]).
```
