### ISSUE TITLE
关于reside-outdoor数据集的问题

### ISSUE THREAD

**Issue by Missing-FEIFEI** [AmeryXiong/MixDehazeNet#13]
您好！我想知道你们是如何选择reside-outdoor数据集的或者说来源是哪里。因为我发现在相关论文里面所用的outdoor数据集内的数据数量是有差异的，有30万张，29万张，以及最初提出reside数据集的论文里面提到的7万多张。希望作者能解释以下，万分感谢！

**Comment by AmeryXiong** [comment]
您好，我的论文在数据集介绍部分没有写仔细，您可以参考《Vision transformers for single image dehazing》中数据集的介绍，那里面可以解决你的疑问。

**Comment by Missing-FEIFEI** [comment]
好的，谢谢您！
